name: Run WiFi GeoMapper

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      WIGLE_API_NAME: ${{ secrets.WIGLE_API_NAME }}
      WIGLE_API_TOKEN: ${{ secrets.WIGLE_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug files
        run: |
          pwd
          ls -al
          echo "Current path above. Confirming if requirements.txt is here."
          
      - name: Debug file structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Root contents:"
          ls -al
          echo "Recursive listing:"
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: ./  #  use the repo root
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run WiFi GeoMapper
        working-directory: ./  # run from repo root
        run: python main.py
